language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer install --prefer-dist
  
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --report=full -p -s --standard=scripts/phpcs/DPF src tests
